define([
	"./strings",
	"./base64",
	"./camel-case",
	"./dasherize",
	"./deserialize-value",
	"./escape-html",
	"./generate-uuid",
	"./lower-first",
	"./ltrim",
	"./rtrim",
	"./serialize-value",
	"./slugify",
	"./substitute",
	"./trim-null",
	"./unique-id",
	"./upper-first",
	"./words"
],function(strings){
	return strings;
});